<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../DesktopGuardPro.Native/AnalysisWorkspace.cs" Link="AnalysisWorkspace.cs" />
    <Compile Include="../DesktopGuardPro.Native/ControlMessage.cs" Link="ControlMessage.cs" />
  </ItemGroup>
</Project>
