// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum ObjectDetailMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ObjectDetailOmit = "omit",
    ObjectDetailBasename = "basename",
    ObjectDetailFull = "full",
};

export class RedactionPolicy {
    "objectDetails": ObjectDetailMode;
    "includeProcessKey": boolean;
    "includePayload": boolean;
    "includeUsernames": boolean;
    "includeWindowTitles": boolean;
    "maximumTextLength": number;

    /** Creates a new RedactionPolicy instance. */
    constructor($$source: Partial<RedactionPolicy> = {}) {
        if (!("objectDetails" in $$source)) {
            this["objectDetails"] = ObjectDetailMode.$zero;
        }
        if (!("includeProcessKey" in $$source)) {
            this["includeProcessKey"] = false;
        }
        if (!("includePayload" in $$source)) {
            this["includePayload"] = false;
        }
        if (!("includeUsernames" in $$source)) {
            this["includeUsernames"] = false;
        }
        if (!("includeWindowTitles" in $$source)) {
            this["includeWindowTitles"] = false;
        }
        if (!("maximumTextLength" in $$source)) {
            this["maximumTextLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RedactionPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): RedactionPolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RedactionPolicy($$parsedSource as Partial<RedactionPolicy>);
    }
}

export class VerificationManifest {
    "schemaVersion": number;
    "softwareVersion": string;
    "algorithm": string;
    "reportSha256": string;
    "reportSize": number;
    "mediaType": string;
    "sessionId": string;
    "sessionRevision": number;
    "reportGeneratedUtc": string;
    "integrityVerified": boolean;

    /** Creates a new VerificationManifest instance. */
    constructor($$source: Partial<VerificationManifest> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("softwareVersion" in $$source)) {
            this["softwareVersion"] = "";
        }
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("reportSha256" in $$source)) {
            this["reportSha256"] = "";
        }
        if (!("reportSize" in $$source)) {
            this["reportSize"] = 0;
        }
        if (!("mediaType" in $$source)) {
            this["mediaType"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("sessionRevision" in $$source)) {
            this["sessionRevision"] = 0;
        }
        if (!("reportGeneratedUtc" in $$source)) {
            this["reportGeneratedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("integrityVerified" in $$source)) {
            this["integrityVerified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerificationManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): VerificationManifest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerificationManifest($$parsedSource as Partial<VerificationManifest>);
    }
}
