// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reporting$0 from "../reporting/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as risk$0 from "../risk/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export class AssetDifferenceQueryRequest {
    "sessionId": string;
    "categories"?: domain$0.AssetCategory[];

    /** Creates a new AssetDifferenceQueryRequest instance. */
    constructor($$source: Partial<AssetDifferenceQueryRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDifferenceQueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetDifferenceQueryRequest {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField1_0($$parsedSource["categories"]);
        }
        return new AssetDifferenceQueryRequest($$parsedSource as Partial<AssetDifferenceQueryRequest>);
    }
}

export class AssetDifferenceResult {
    "sessionId": string;
    "baselineAvailable": boolean;
    "differences": domain$0.AssetDifference[];

    /** Creates a new AssetDifferenceResult instance. */
    constructor($$source: Partial<AssetDifferenceResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("baselineAvailable" in $$source)) {
            this["baselineAvailable"] = false;
        }
        if (!("differences" in $$source)) {
            this["differences"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDifferenceResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetDifferenceResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("differences" in $$parsedSource) {
            $$parsedSource["differences"] = $$createField2_0($$parsedSource["differences"]);
        }
        return new AssetDifferenceResult($$parsedSource as Partial<AssetDifferenceResult>);
    }
}

export class DirectoryMonitoringResult {
    "directories": string[];
    "targets"?: domain$0.MonitoringTarget[];
    "exclusions"?: domain$0.MonitoringExclusion[];
    "inputActivityEnabled"?: boolean | null;
    "windowTitleEnabled"?: boolean | null;
    "highRiskShortcutsEnabled"?: boolean | null;

    /** Creates a new DirectoryMonitoringResult instance. */
    constructor($$source: Partial<DirectoryMonitoringResult> = {}) {
        if (!("directories" in $$source)) {
            this["directories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryMonitoringResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DirectoryMonitoringResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("directories" in $$parsedSource) {
            $$parsedSource["directories"] = $$createField0_0($$parsedSource["directories"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        if ("exclusions" in $$parsedSource) {
            $$parsedSource["exclusions"] = $$createField2_0($$parsedSource["exclusions"]);
        }
        return new DirectoryMonitoringResult($$parsedSource as Partial<DirectoryMonitoringResult>);
    }
}

export class HealthResult {
    "maintenanceGate": boolean;
    "status": string;
    "session"?: domain$0.Session | null;

    /** Creates a new HealthResult instance. */
    constructor($$source: Partial<HealthResult> = {}) {
        if (!("maintenanceGate" in $$source)) {
            this["maintenanceGate"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthResult {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField2_0($$parsedSource["session"]);
        }
        return new HealthResult($$parsedSource as Partial<HealthResult>);
    }
}

export class MonitoringImpactResult {
    "requiresAdministrator": boolean;
    "expectedEventVolume": domain$0.MonitoringImpactLevel;
    "performanceImpact": domain$0.MonitoringImpactLevel;
    "storageImpact": domain$0.MonitoringImpactLevel;

    /** Creates a new MonitoringImpactResult instance. */
    constructor($$source: Partial<MonitoringImpactResult> = {}) {
        if (!("requiresAdministrator" in $$source)) {
            this["requiresAdministrator"] = false;
        }
        if (!("expectedEventVolume" in $$source)) {
            this["expectedEventVolume"] = domain$0.MonitoringImpactLevel.$zero;
        }
        if (!("performanceImpact" in $$source)) {
            this["performanceImpact"] = domain$0.MonitoringImpactLevel.$zero;
        }
        if (!("storageImpact" in $$source)) {
            this["storageImpact"] = domain$0.MonitoringImpactLevel.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitoringImpactResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitoringImpactResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitoringImpactResult($$parsedSource as Partial<MonitoringImpactResult>);
    }
}

export class ReportExportRequest {
    "fromSequence"?: number;
    "toSequence"?: number;
    "sessionId": string;
    "format": ReportFormat;
    "redaction": reporting$0.RedactionPolicy;

    /** Creates a new ReportExportRequest instance. */
    constructor($$source: Partial<ReportExportRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = ReportFormat.$zero;
        }
        if (!("redaction" in $$source)) {
            this["redaction"] = (new reporting$0.RedactionPolicy());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportExportRequest {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField4_0($$parsedSource["redaction"]);
        }
        return new ReportExportRequest($$parsedSource as Partial<ReportExportRequest>);
    }
}

export enum ReportFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReportFormatHTML = "html",
    ReportFormatMarkdown = "markdown",
    ReportFormatJSON = "json",
};

export class ReportResult {
    "format": ReportFormat;
    "mediaType": string;
    "content"?: string;
    "transfer"?: ReportTransfer | null;
    "verification"?: reporting$0.VerificationManifest | null;
    "generatedUtc": string;

    /** Creates a new ReportResult instance. */
    constructor($$source: Partial<ReportResult> = {}) {
        if (!("format" in $$source)) {
            this["format"] = ReportFormat.$zero;
        }
        if (!("mediaType" in $$source)) {
            this["mediaType"] = "";
        }
        if (!("generatedUtc" in $$source)) {
            this["generatedUtc"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportResult {
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transfer" in $$parsedSource) {
            $$parsedSource["transfer"] = $$createField3_0($$parsedSource["transfer"]);
        }
        if ("verification" in $$parsedSource) {
            $$parsedSource["verification"] = $$createField4_0($$parsedSource["verification"]);
        }
        return new ReportResult($$parsedSource as Partial<ReportResult>);
    }
}

export class ReportTransfer {
    "token": string;
    "size": number;
    "sha256": string;
    "chunkBytes": number;
    "expiresUtc": string;

    /** Creates a new ReportTransfer instance. */
    constructor($$source: Partial<ReportTransfer> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("chunkBytes" in $$source)) {
            this["chunkBytes"] = 0;
        }
        if (!("expiresUtc" in $$source)) {
            this["expiresUtc"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportTransfer instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportTransfer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportTransfer($$parsedSource as Partial<ReportTransfer>);
    }
}

export class RiskFindingStatusResult {
    "sessionId": string;
    "findingId": string;
    "status": risk$0.FindingStatus;

    /** Creates a new RiskFindingStatusResult instance. */
    constructor($$source: Partial<RiskFindingStatusResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("findingId" in $$source)) {
            this["findingId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = risk$0.FindingStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RiskFindingStatusResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RiskFindingStatusResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RiskFindingStatusResult($$parsedSource as Partial<RiskFindingStatusResult>);
    }
}

export class RiskFindingStatusUpdateRequest {
    "sessionId": string;
    "findingId": string;
    "status": risk$0.FindingStatus;

    /** Creates a new RiskFindingStatusUpdateRequest instance. */
    constructor($$source: Partial<RiskFindingStatusUpdateRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("findingId" in $$source)) {
            this["findingId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = risk$0.FindingStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RiskFindingStatusUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RiskFindingStatusUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RiskFindingStatusUpdateRequest($$parsedSource as Partial<RiskFindingStatusUpdateRequest>);
    }
}

export class SessionBaselineReviewResult {
    "sessionId": string;
    "decision": domain$0.BaselineStartDecision;
    "resolution"?: storage$0.BaselineReviewResolution;
    "session"?: domain$0.Session | null;

    /** Creates a new SessionBaselineReviewResult instance. */
    constructor($$source: Partial<SessionBaselineReviewResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("decision" in $$source)) {
            this["decision"] = (new domain$0.BaselineStartDecision());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionBaselineReviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionBaselineReviewResult {
        const $$createField1_0 = $$createType15;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("decision" in $$parsedSource) {
            $$parsedSource["decision"] = $$createField1_0($$parsedSource["decision"]);
        }
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField3_0($$parsedSource["session"]);
        }
        return new SessionBaselineReviewResult($$parsedSource as Partial<SessionBaselineReviewResult>);
    }
}

export class SessionResult {
    "session"?: domain$0.Session | null;

    /** Creates a new SessionResult instance. */
    constructor($$source: Partial<SessionResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionResult {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SessionResult($$parsedSource as Partial<SessionResult>);
    }
}

export class SessionRetentionLockRequest {
    "sessionId": string;
    "locked": boolean;

    /** Creates a new SessionRetentionLockRequest instance. */
    constructor($$source: Partial<SessionRetentionLockRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRetentionLockRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRetentionLockRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRetentionLockRequest($$parsedSource as Partial<SessionRetentionLockRequest>);
    }
}

export class SessionRetentionLockResult {
    "sessionId": string;
    "locked": boolean;

    /** Creates a new SessionRetentionLockResult instance. */
    constructor($$source: Partial<SessionRetentionLockResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRetentionLockResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRetentionLockResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRetentionLockResult($$parsedSource as Partial<SessionRetentionLockResult>);
    }
}

export class SessionRetentionPruneRequest {
    "beforeUtc": string;
    "limit"?: number;

    /** Creates a new SessionRetentionPruneRequest instance. */
    constructor($$source: Partial<SessionRetentionPruneRequest> = {}) {
        if (!("beforeUtc" in $$source)) {
            this["beforeUtc"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRetentionPruneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRetentionPruneRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRetentionPruneRequest($$parsedSource as Partial<SessionRetentionPruneRequest>);
    }
}

export class SessionRetentionPruneResult {
    "deletedSessionIds": string[];

    /** Creates a new SessionRetentionPruneResult instance. */
    constructor($$source: Partial<SessionRetentionPruneResult> = {}) {
        if (!("deletedSessionIds" in $$source)) {
            this["deletedSessionIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRetentionPruneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRetentionPruneResult {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deletedSessionIds" in $$parsedSource) {
            $$parsedSource["deletedSessionIds"] = $$createField0_0($$parsedSource["deletedSessionIds"]);
        }
        return new SessionRetentionPruneResult($$parsedSource as Partial<SessionRetentionPruneResult>);
    }
}

export class SessionStartPreviewResult {
    "monitoringLevel": domain$0.MonitoringLevel;
    "monitoredTargetCount": number;
    "targets": domain$0.MonitoringTarget[];
    "impact": MonitoringImpactResult;

    /** Creates a new SessionStartPreviewResult instance. */
    constructor($$source: Partial<SessionStartPreviewResult> = {}) {
        if (!("monitoringLevel" in $$source)) {
            this["monitoringLevel"] = domain$0.MonitoringLevel.$zero;
        }
        if (!("monitoredTargetCount" in $$source)) {
            this["monitoredTargetCount"] = 0;
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }
        if (!("impact" in $$source)) {
            this["impact"] = (new MonitoringImpactResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStartPreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionStartPreviewResult {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField2_0($$parsedSource["targets"]);
        }
        if ("impact" in $$parsedSource) {
            $$parsedSource["impact"] = $$createField3_0($$parsedSource["impact"]);
        }
        return new SessionStartPreviewResult($$parsedSource as Partial<SessionStartPreviewResult>);
    }
}

export class TimelineQueryRequest {
    "sessionId": string;
    "cursor"?: string;
    "limit"?: number;
    "categories"?: domain$0.EventCategory[];
    "severities"?: domain$0.EventSeverity[];
    "userSidHash"?: string;
    "user"?: string;
    "process"?: string;
    "path"?: string;
    "fromUtc"?: string | null;
    "toUtc"?: string | null;

    /** Creates a new TimelineQueryRequest instance. */
    constructor($$source: Partial<TimelineQueryRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineQueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineQueryRequest {
        const $$createField3_0 = $$createType17;
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField3_0($$parsedSource["categories"]);
        }
        if ("severities" in $$parsedSource) {
            $$parsedSource["severities"] = $$createField4_0($$parsedSource["severities"]);
        }
        return new TimelineQueryRequest($$parsedSource as Partial<TimelineQueryRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = domain$0.AssetDifference.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = domain$0.MonitoringTarget.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = domain$0.MonitoringExclusion.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = domain$0.Session.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = reporting$0.RedactionPolicy.createFrom;
const $$createType11 = ReportTransfer.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = reporting$0.VerificationManifest.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = domain$0.BaselineStartDecision.createFrom;
const $$createType16 = MonitoringImpactResult.createFrom;
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = $Create.Array($Create.Any);
