// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Asset {
    "category": AssetCategory;
    "identifier": string;
    "displayName": string;
    "attributes"?: { [_ in string]?: string };

    /** Creates a new Asset instance. */
    constructor($$source: Partial<Asset> = {}) {
        if (!("category" in $$source)) {
            this["category"] = AssetCategory.$zero;
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     */
    static createFrom($$source: any = {}): Asset {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField3_0($$parsedSource["attributes"]);
        }
        return new Asset($$parsedSource as Partial<Asset>);
    }
}

export enum AssetCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AssetCategorySoftware = "software",
    AssetCategoryDevice = "device",
    AssetCategoryNetwork = "network",
    AssetCategoryAccount = "account",
    AssetCategorySystem = "system",
};

export class AssetDifference {
    "kind": AssetDifferenceKind;
    "presenceStatus"?: string;
    "before"?: Asset | null;
    "after"?: Asset | null;
    "changedAttributes"?: string[];

    /** Creates a new AssetDifference instance. */
    constructor($$source: Partial<AssetDifference> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = AssetDifferenceKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDifference instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetDifference {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("before" in $$parsedSource) {
            $$parsedSource["before"] = $$createField2_0($$parsedSource["before"]);
        }
        if ("after" in $$parsedSource) {
            $$parsedSource["after"] = $$createField3_0($$parsedSource["after"]);
        }
        if ("changedAttributes" in $$parsedSource) {
            $$parsedSource["changedAttributes"] = $$createField4_0($$parsedSource["changedAttributes"]);
        }
        return new AssetDifference($$parsedSource as Partial<AssetDifference>);
    }
}

export enum AssetDifferenceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AssetDifferenceAdded = "added",
    AssetDifferenceRemoved = "removed",
    AssetDifferenceChanged = "changed",
};

export class AuditEvent {
    "eventId": string;
    "sessionId": string;
    "sequence": number;
    "category": EventCategory;
    "action": string;
    "severity": EventSeverity;
    "observedUtc": string;
    "monotonicTicks": number;
    "windowsSessionId"?: number | null;
    "userSidHash"?: string;
    "processKey"?: string;
    "objectKey"?: string;
    "source": string;
    "confidence": EventConfidence;
    "encryptedPayload"?: string;
    "previousHash"?: string;
    "eventHash"?: string;

    /** Creates a new AuditEvent instance. */
    constructor($$source: Partial<AuditEvent> = {}) {
        if (!("eventId" in $$source)) {
            this["eventId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("category" in $$source)) {
            this["category"] = EventCategory.$zero;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = EventSeverity.$zero;
        }
        if (!("observedUtc" in $$source)) {
            this["observedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("monotonicTicks" in $$source)) {
            this["monotonicTicks"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = EventConfidence.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditEvent {
        const $$createField9_0 = $Create.ByteSlice;
        const $$createField14_0 = $Create.ByteSlice;
        const $$createField15_0 = $Create.ByteSlice;
        const $$createField16_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userSidHash" in $$parsedSource) {
            $$parsedSource["userSidHash"] = $$createField9_0($$parsedSource["userSidHash"]);
        }
        if ("encryptedPayload" in $$parsedSource) {
            $$parsedSource["encryptedPayload"] = $$createField14_0($$parsedSource["encryptedPayload"]);
        }
        if ("previousHash" in $$parsedSource) {
            $$parsedSource["previousHash"] = $$createField15_0($$parsedSource["previousHash"]);
        }
        if ("eventHash" in $$parsedSource) {
            $$parsedSource["eventHash"] = $$createField16_0($$parsedSource["eventHash"]);
        }
        return new AuditEvent($$parsedSource as Partial<AuditEvent>);
    }
}

export class BaselineCaptureFailure {
    "item": string;
    "reason": string;

    /** Creates a new BaselineCaptureFailure instance. */
    constructor($$source: Partial<BaselineCaptureFailure> = {}) {
        if (!("item" in $$source)) {
            this["item"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaselineCaptureFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): BaselineCaptureFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BaselineCaptureFailure($$parsedSource as Partial<BaselineCaptureFailure>);
    }
}

export enum BaselineCaptureStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BaselineCaptureStatusSucceeded = "succeeded",
    BaselineCaptureStatusPartialFailure = "partial_failure",
    BaselineCaptureStatusFailed = "failed",
};

export class BaselineStartDecision {
    "status": BaselineCaptureStatus;
    "failures"?: BaselineCaptureFailure[];
    "requiresUserChoice": boolean;
    "canContinue": boolean;
    "canCancel": boolean;

    /** Creates a new BaselineStartDecision instance. */
    constructor($$source: Partial<BaselineStartDecision> = {}) {
        if (!("status" in $$source)) {
            this["status"] = BaselineCaptureStatus.$zero;
        }
        if (!("requiresUserChoice" in $$source)) {
            this["requiresUserChoice"] = false;
        }
        if (!("canContinue" in $$source)) {
            this["canContinue"] = false;
        }
        if (!("canCancel" in $$source)) {
            this["canCancel"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaselineStartDecision instance from a string or object.
     */
    static createFrom($$source: any = {}): BaselineStartDecision {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField1_0($$parsedSource["failures"]);
        }
        return new BaselineStartDecision($$parsedSource as Partial<BaselineStartDecision>);
    }
}

export enum EventCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventCategoryFile = "file",
    EventCategoryProcess = "process",
    EventCategorySoftware = "software",
    EventCategorySystem = "system",
    EventCategoryDevice = "device",
    EventCategoryHealth = "health",
};

export enum EventConfidence {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventConfidenceDirect = "direct",
    EventConfidenceCorrelated = "correlated",
    EventConfidenceSnapshotDiff = "snapshot_diff",
};

export enum EventSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventSeverityLow = "low",
    EventSeverityMedium = "medium",
    EventSeverityHigh = "high",
};

export class MonitoringExclusion {
    "kind": MonitoringExclusionKind;
    "pattern": string;

    /** Creates a new MonitoringExclusion instance. */
    constructor($$source: Partial<MonitoringExclusion> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = MonitoringExclusionKind.$zero;
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitoringExclusion instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitoringExclusion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitoringExclusion($$parsedSource as Partial<MonitoringExclusion>);
    }
}

export enum MonitoringExclusionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MonitoringExclusionKindPath = "path",
    MonitoringExclusionKindFileName = "file_name",
    MonitoringExclusionKindExtension = "extension",
    MonitoringExclusionKindProcess = "process",
};

export enum MonitoringImpactLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MonitoringImpactLow = "low",
    MonitoringImpactMedium = "medium",
    MonitoringImpactHigh = "high",
};

export enum MonitoringLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MonitoringLevelStandard = "standard",
    MonitoringLevelStrict = "strict",
};

export class MonitoringTarget {
    "path": string;
    "kind": MonitoringTargetKind;
    "recursive": boolean;
    "configuredPath"?: string;
    "resolutionStatus"?: MonitoringTargetResolutionStatus;
    "resolutionDetail"?: string;

    /** Creates a new MonitoringTarget instance. */
    constructor($$source: Partial<MonitoringTarget> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = MonitoringTargetKind.$zero;
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitoringTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitoringTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitoringTarget($$parsedSource as Partial<MonitoringTarget>);
    }
}

export enum MonitoringTargetKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MonitoringTargetKindDirectory = "directory",
    MonitoringTargetKindFile = "file",
    MonitoringTargetKindRemovableVolume = "removable_volume",
};

export enum MonitoringTargetResolutionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MonitoringTargetResolutionAvailable = "available",
    MonitoringTargetResolutionReparseResolved = "reparse_resolved",
};

export class Session {
    "ID": string;
    "Name": string;
    "State": SessionState;
    "Revision": number;
    "MonitoringLevel": MonitoringLevel;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("State" in $$source)) {
            this["State"] = SessionState.$zero;
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("MonitoringLevel" in $$source)) {
            this["MonitoringLevel"] = MonitoringLevel.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

export enum SessionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionStateDraft = "draft",
    SessionStatePreparing = "preparing",
    SessionStateBaselineReview = "baseline_review",
    SessionStateActive = "active",
    SessionStateDegraded = "degraded",
    SessionStatePaused = "paused",
    SessionStateFinalizing = "finalizing",
    SessionStateCompleted = "completed",
    SessionStateFailed = "failed",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Asset.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = BaselineCaptureFailure.createFrom;
const $$createType5 = $Create.Array($$createType4);
