// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export enum BaselineReviewResolution {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BaselineReviewResolutionContinue = "continue",
    BaselineReviewResolutionCancel = "cancel",
};

export class EventRecord {
    "Event": domain$0.AuditEvent;
    "Payload": string;
    "previewTruncated"?: boolean;

    /** Creates a new EventRecord instance. */
    constructor($$source: Partial<EventRecord> = {}) {
        if (!("Event" in $$source)) {
            this["Event"] = (new domain$0.AuditEvent());
        }
        if (!("Payload" in $$source)) {
            this["Payload"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): EventRecord {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Event" in $$parsedSource) {
            $$parsedSource["Event"] = $$createField0_0($$parsedSource["Event"]);
        }
        if ("Payload" in $$parsedSource) {
            $$parsedSource["Payload"] = $$createField1_0($$parsedSource["Payload"]);
        }
        return new EventRecord($$parsedSource as Partial<EventRecord>);
    }
}

export class SessionListItem {
    "session": domain$0.Session;
    "createdUtc": string;
    "updatedUtc": string;
    "retentionLocked": boolean;

    /** Creates a new SessionListItem instance. */
    constructor($$source: Partial<SessionListItem> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new domain$0.Session());
        }
        if (!("createdUtc" in $$source)) {
            this["createdUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedUtc" in $$source)) {
            this["updatedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("retentionLocked" in $$source)) {
            this["retentionLocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionListItem {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SessionListItem($$parsedSource as Partial<SessionListItem>);
    }
}

export class SessionListPage {
    "items": SessionListItem[];
    "hasMore": boolean;
    "nextCursor"?: string;

    /** Creates a new SessionListPage instance. */
    constructor($$source: Partial<SessionListPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionListPage instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionListPage {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SessionListPage($$parsedSource as Partial<SessionListPage>);
    }
}

export class TimelinePage {
    "integrityScope"?: string;
    "scannedEvents": number;
    "records": EventRecord[];
    "nextCursor"?: string;
    "hasMore": boolean;
    "integrityVerified": boolean;

    /** Creates a new TimelinePage instance. */
    constructor($$source: Partial<TimelinePage> = {}) {
        if (!("scannedEvents" in $$source)) {
            this["scannedEvents"] = 0;
        }
        if (!("records" in $$source)) {
            this["records"] = [];
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }
        if (!("integrityVerified" in $$source)) {
            this["integrityVerified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelinePage instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelinePage {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField2_0($$parsedSource["records"]);
        }
        return new TimelinePage($$parsedSource as Partial<TimelinePage>);
    }
}

// Private type creation functions
const $$createType0 = domain$0.AuditEvent.createFrom;
const $$createType1 = domain$0.Session.createFrom;
const $$createType2 = SessionListItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = EventRecord.createFrom;
const $$createType5 = $Create.Array($$createType4);
