// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export class Evaluation {
    "eventCount": number;
    "coverageGapCount": number;
    "sessionId": string;
    "findings": Finding[];
    "failures"?: RuleFailure[];
    "ruleVersions"?: RuleVersion[];

    /** Creates a new Evaluation instance. */
    constructor($$source: Partial<Evaluation> = {}) {
        if (!("eventCount" in $$source)) {
            this["eventCount"] = 0;
        }
        if (!("coverageGapCount" in $$source)) {
            this["coverageGapCount"] = 0;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Evaluation instance from a string or object.
     */
    static createFrom($$source: any = {}): Evaluation {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField3_0($$parsedSource["findings"]);
        }
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField4_0($$parsedSource["failures"]);
        }
        if ("ruleVersions" in $$parsedSource) {
            $$parsedSource["ruleVersions"] = $$createField5_0($$parsedSource["ruleVersions"]);
        }
        return new Evaluation($$parsedSource as Partial<Evaluation>);
    }
}

export class EvidenceReference {
    "eventId": string;
    "sequence": number;
    "observedUtc": string;
    "category": domain$0.EventCategory;
    "action": string;
    "objectKey"?: string;

    /** Creates a new EvidenceReference instance. */
    constructor($$source: Partial<EvidenceReference> = {}) {
        if (!("eventId" in $$source)) {
            this["eventId"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("observedUtc" in $$source)) {
            this["observedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("category" in $$source)) {
            this["category"] = domain$0.EventCategory.$zero;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EvidenceReference instance from a string or object.
     */
    static createFrom($$source: any = {}): EvidenceReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EvidenceReference($$parsedSource as Partial<EvidenceReference>);
    }
}

export class Finding {
    "id": string;
    "ruleId": string;
    "key": string;
    "sessionId": string;
    "title": string;
    "summary": string;
    "level": Level;
    "score": number;
    "confidence": number;
    "status": FindingStatus;
    "firstObservedUtc": string;
    "lastObservedUtc": string;
    "evidence": EvidenceReference[];
    "tags"?: string[];

    /** Creates a new Finding instance. */
    constructor($$source: Partial<Finding> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ruleId" in $$source)) {
            this["ruleId"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = Level.$zero;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = FindingStatus.$zero;
        }
        if (!("firstObservedUtc" in $$source)) {
            this["firstObservedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastObservedUtc" in $$source)) {
            this["lastObservedUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     */
    static createFrom($$source: any = {}): Finding {
        const $$createField12_0 = $$createType7;
        const $$createField13_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField12_0($$parsedSource["evidence"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField13_0($$parsedSource["tags"]);
        }
        return new Finding($$parsedSource as Partial<Finding>);
    }
}

export enum FindingStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FindingStatusKnown = "known",
    FindingStatusPendingReview = "pending_review",
    FindingStatusActionNeeded = "action_needed",
};

export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelInformational = "informational",
    LevelLow = "low",
    LevelMedium = "medium",
    LevelHigh = "high",
    LevelCritical = "critical",
};

export class RuleFailure {
    "ruleId": string;
    "message": string;

    /** Creates a new RuleFailure instance. */
    constructor($$source: Partial<RuleFailure> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleFailure($$parsedSource as Partial<RuleFailure>);
    }
}

export class RuleVersion {
    "ruleId": string;
    "version": string;

    /** Creates a new RuleVersion instance. */
    constructor($$source: Partial<RuleVersion> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleVersion($$parsedSource as Partial<RuleVersion>);
    }
}

// Private type creation functions
const $$createType0 = Finding.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RuleFailure.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = RuleVersion.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = EvidenceReference.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
