// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as risk$0 from "../risk/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export function CreateSession(id: string, name: string): $CancellablePromise<service$0.SessionResult> {
    return $Call.ByID(2008162145, id, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateSessionWithMonitoringLevel(id: string, name: string, level: domain$0.MonitoringLevel): $CancellablePromise<service$0.SessionResult> {
    return $Call.ByID(1076536295, id, name, level).then(($result: any) => {
        return $$createType0($result);
    });
}

export function EndSession(): $CancellablePromise<service$0.SessionResult> {
    return $Call.ByID(750397240).then(($result: any) => {
        return $$createType0($result);
    });
}

export function EvaluateRisk(sessionID: string): $CancellablePromise<risk$0.Evaluation> {
    return $Call.ByID(1731665475, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExportReport(request: service$0.ReportExportRequest): $CancellablePromise<service$0.ReportResult> {
    return $Call.ByID(1214460563, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetCurrentSession(): $CancellablePromise<service$0.SessionResult> {
    return $Call.ByID(3695003002).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDirectoryMonitoring(): $CancellablePromise<service$0.DirectoryMonitoringResult> {
    return $Call.ByID(3120064422).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetHealth(): $CancellablePromise<service$0.HealthResult> {
    return $Call.ByID(1139140395).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSessionBaselineReview(sessionID: string): $CancellablePromise<service$0.SessionBaselineReviewResult> {
    return $Call.ByID(606390144, sessionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSessionStartPreview(level: domain$0.MonitoringLevel): $CancellablePromise<service$0.SessionStartPreviewResult> {
    return $Call.ByID(1864301603, level).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListSessions(cursor: string): $CancellablePromise<storage$0.SessionListPage> {
    return $Call.ByID(3047131446, cursor).then(($result: any) => {
        return $$createType7($result);
    });
}

export function PruneSessionRetention(request: service$0.SessionRetentionPruneRequest): $CancellablePromise<service$0.SessionRetentionPruneResult> {
    return $Call.ByID(1741430655, request).then(($result: any) => {
        return $$createType8($result);
    });
}

export function QueryAssetDifferences(request: service$0.AssetDifferenceQueryRequest): $CancellablePromise<service$0.AssetDifferenceResult> {
    return $Call.ByID(2471745173, request).then(($result: any) => {
        return $$createType9($result);
    });
}

export function QueryTimeline(request: service$0.TimelineQueryRequest): $CancellablePromise<storage$0.TimelinePage> {
    return $Call.ByID(1441076838, request).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ResolveSessionBaselineReview(sessionID: string, resolution: storage$0.BaselineReviewResolution): $CancellablePromise<service$0.SessionBaselineReviewResult> {
    return $Call.ByID(401541056, sessionID, resolution).then(($result: any) => {
        return $$createType5($result);
    });
}

export function TransitionSession(state: domain$0.SessionState): $CancellablePromise<service$0.SessionResult> {
    return $Call.ByID(959149068, state).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateDirectoryMonitoring(directories: string[]): $CancellablePromise<service$0.DirectoryMonitoringResult> {
    return $Call.ByID(3110059751, directories).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateMonitoringTargets(targets: domain$0.MonitoringTarget[]): $CancellablePromise<service$0.DirectoryMonitoringResult> {
    return $Call.ByID(3646364134, targets).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateRiskFindingStatus(request: service$0.RiskFindingStatusUpdateRequest): $CancellablePromise<service$0.RiskFindingStatusResult> {
    return $Call.ByID(2895833736, request).then(($result: any) => {
        return $$createType11($result);
    });
}

export function UpdateSessionRetentionLock(request: service$0.SessionRetentionLockRequest): $CancellablePromise<service$0.SessionRetentionLockResult> {
    return $Call.ByID(1975664703, request).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = service$0.SessionResult.createFrom;
const $$createType1 = risk$0.Evaluation.createFrom;
const $$createType2 = service$0.ReportResult.createFrom;
const $$createType3 = service$0.DirectoryMonitoringResult.createFrom;
const $$createType4 = service$0.HealthResult.createFrom;
const $$createType5 = service$0.SessionBaselineReviewResult.createFrom;
const $$createType6 = service$0.SessionStartPreviewResult.createFrom;
const $$createType7 = storage$0.SessionListPage.createFrom;
const $$createType8 = service$0.SessionRetentionPruneResult.createFrom;
const $$createType9 = service$0.AssetDifferenceResult.createFrom;
const $$createType10 = storage$0.TimelinePage.createFrom;
const $$createType11 = service$0.RiskFindingStatusResult.createFrom;
const $$createType12 = service$0.SessionRetentionLockResult.createFrom;
